const {
  NEXTAUTH_URL_DEV,
  NEXTAUTH_URL_PRODUCTION,
  MONGODB_URI_DEV,
  MONGODB_URI,
  MONGODB_DB,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  JWT_SECRET,
  JWT_SIGNING_PRIVATE_KEY,
} = process.env;

const DB_URI = process.env.NODE_ENV === "development" ? MONGODB_URI_DEV : MONGODB_URI;

const NEXTAUTH_URL =
  process.env.NODE_ENV === "development" ? NEXTAUTH_URL_DEV : NEXTAUTH_URL_PRODUCTION;

export default {
  DB_URI,
  MONGODB_DB,
  NEXTAUTH_URL,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  JWT_SECRET,
  JWT_SIGNING_PRIVATE_KEY,
};
